#pragma config(UserModel, "E:/VIQC Code/Lib/Header.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "GREENING_DRIVE.c"
#include "GREENING_ARM.c"
#include "GREENING_MATH.c"
#include "GREENING_ESTOP.c"

task main()
{




}
